name: Profiling Test

on:
  workflow_dispatch:
    inputs:
      versionNumber:
        description: 'Version number'
        default: '0.0.0'
        required: true
        type: string
      versionCode:
        description: 'Version code'
        default: '0'
        required: true
        type: string

jobs:
  profiling:
    runs-on: profiler
    permissions:
      contents: 'write'
      id-token: 'write'

    steps:
      - name: Check Out
        uses: actions/checkout@v3
      - name: Install Dependencies
        id: install
        run: npm ci
      - uses: ./
        id: profiling
        with:
          credentials: ${{ secrets.GCP_CREDENTIALS }}
          bucketName: ${{ secrets.BUCKET_NAME }}
          packageName: ${{ secrets.PACKAGE_NAME }}
          versionNumber: ${{ inputs.versionNumber }}
          versionCode: ${{ inputs.versionCode }}
      - name: GCP Cloud Auth
        id: 'gcp-cloud-auth'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
      - name: Upload to GCP Cloud
        id: 'upload-to-gcp-cloud'
        uses: 'google-github-actions/upload-cloud-storage@v1'
        with:
          path: ${{ steps.profiling.outputs.resultsPath }}
          destination: ${{ format('{0}/{1}', secrets.BUCKET_NAME, 'ProfilingResults') }}
          process_gcloudignore: false